apiVersion: v1
kind: Namespace
metadata:
  name: merlin-system
  labels:
    name: merlin-system
    app: merlin-ai-router
    tier: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: merlin-dev
  labels:
    name: merlin-dev
    app: merlin-ai-router
    tier: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: merlin-staging
  labels:
    name: merlin-staging
    app: merlin-ai-router
    tier: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: merlin-prod
  labels:
    name: merlin-prod
    app: merlin-ai-router
    tier: production